// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfoeNgx6otaCJK6uoM5VyNx2fuBTQhdhw',
    appId: '1:571197394470:web:fe58118724105c9e8120e7',
    messagingSenderId: '571197394470',
    projectId: 'chat-app-57972',
    authDomain: 'chat-app-57972.firebaseapp.com',
    storageBucket: 'chat-app-57972.firebasestorage.app',
    measurementId: 'G-0VM8RQVC3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp0f2uaszPIjWq4ArJpNY__3uBxn_ZVNs',
    appId: '1:571197394470:android:97e772be4168ec148120e7',
    messagingSenderId: '571197394470',
    projectId: 'chat-app-57972',
    storageBucket: 'chat-app-57972.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZeD7dXgZrYpndchP7fx0gjVlLJ3Emh6k',
    appId: '1:571197394470:ios:6eabdee6e59310168120e7',
    messagingSenderId: '571197394470',
    projectId: 'chat-app-57972',
    storageBucket: 'chat-app-57972.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZeD7dXgZrYpndchP7fx0gjVlLJ3Emh6k',
    appId: '1:571197394470:ios:6eabdee6e59310168120e7',
    messagingSenderId: '571197394470',
    projectId: 'chat-app-57972',
    storageBucket: 'chat-app-57972.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfoeNgx6otaCJK6uoM5VyNx2fuBTQhdhw',
    appId: '1:571197394470:web:c4d55fc79f2629f68120e7',
    messagingSenderId: '571197394470',
    projectId: 'chat-app-57972',
    authDomain: 'chat-app-57972.firebaseapp.com',
    storageBucket: 'chat-app-57972.firebasestorage.app',
    measurementId: 'G-FZXD2GTQTH',
  );
}
